<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import mlflow
import numpy as np

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

In [3]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3

In [4]:
model1 = LinearRegression()

model1.fit(X,y)

model1.predict(X)


array([ 6.,  8.,  9., 11.])

In [5]:
mlflow.sklearn.autolog()

model1 = LinearRegression()
with mlflow.start_run() as run:
    model1.fit(X,y)
    print("Logged data and model in run {}".format(run.info.run_id))
    
model1.predict(X)

Logged data and model in run c30f620ade224208a1fefe15798c8dc4


array([ 6.,  8.,  9., 11.])

In [6]:
mlflow.sklearn.autolog(disable = True)



In [7]:
model2 = DecisionTreeRegressor()

model2.fit(X,y)

model2.predict(X)

array([ 6.,  8.,  9., 11.])

In [8]:
mlflow.sklearn.autolog()
model1 = DecisionTreeRegressor()
with mlflow.start_run() as run:
    model1.fit(X,y)
    print("Logged data and model in run {}".format(run.info.run_id))
    
model1.predict(X)

Logged data and model in run a44292459ae54ca8847ada34ea84721f


array([ 6.,  8.,  9., 11.])

In [22]:
model2 = DecisionTreeRegressor(max_depth = 2, min_samples_split=1)

In [9]:
mlflow.sklearn.autolog(disable = True)

In [10]:
mlflow.set_experiment("test_experiment")

model2 = DecisionTreeRegressor(max_depth = 2, min_samples_split=2)

with mlflow.start_run() as run2:


    model2.fit(X,y)

    model2.predict(X)
    
    mlflow.log_param('max_depth', model2.get_params()['max_depth'])
    mlflow.log_param('max_depth', model2.get_params()['min_samples_split'])
    
    mlflow.log_param("my", "param")
    mlflow.log_metric("score", 100)