<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [3]:
import mlflow
import numpy as np

In [10]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

import mlflow

In [4]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3

In [13]:
model1 = LinearRegression()

model1.fit(X,y)

model1.predict(X)


array([ 6.,  8.,  9., 11.])

In [20]:
mlflow.sklearn.autolog()

model1 = DecisionTreeRegressor()
with mlflow.start_run() as run:
    model1.fit(X,y)
    #print("Logged data and model in run {}".format(run.info.run_id))
    
model1.predict(X)

Logged data and model in run 9c6a27f0fe84494c9e3cb7bf172edaca


array([ 6.,  8.,  9., 11.])

In [16]:
model2 = DecisionTreeRegressor()

model2.fit(X,y)

model2.predict(X)

array([ 6.,  8.,  9., 11.])

In [ ]:
model1 = DecisionTreeRegressor()
with mlflow.start_run() as run:
    model1.fit(X,y)
    print("Logged data and model in run {}".format(run.info.run_id))
    
model1.predict(X)

In [22]:
model2 = DecisionTreeRegressor(max_depth = 2, min_samples_split=1)

In [27]:
mlflow.set_experiment("test_experiment")

model2 = DecisionTreeRegressor(max_depth = 2, min_samples_split=2)

with mlflow.start_run() as run2:


    model2.fit(X,y)

    model2.predict(X)
    
    mlflow.log_param('max_depth', model2.get_params()['max_depth'])
    mlflow.log_param('max_depth', model2.get_params()['min_samples_split'])