Proprietary content. ©Great Learning. All Rights Reserved. Unauthorized use or distribution prohibited

In [4]:
import numpy as np

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
# list of text documents
text = ['This is the first stage of qualification'
, 'This is the second stage of qualification '
, 'And the third one'
, 'Is it the first stage again']
# create the transform
vectorizer = CountVectorizer(analyzer='word', binary=False, decode_error='strict',
dtype=np.int64, encoding='utf-8', input='content',
lowercase=True, max_df=1.0, max_features=None, min_df=1,
ngram_range=(1, 1), preprocessor=None, stop_words=None,
strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
tokenizer=None, vocabulary=None)
# tokenize and build vocab
vectorizer.fit(text)
# summarize
print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(text)
# summarize encoded vector
print(vector.shape)
print(type(vector))
print(vector.toarray())

{'this': 12, 'is': 3, 'the': 10, 'first': 2, 'stage': 9, 'of': 5, 'qualification': 7, 'second': 8, 'and': 1, 'third': 11, 'one': 6, 'it': 4, 'again': 0}
(4, 13)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 1 1 0 1 0 1 0 1 1 0 1]
 [0 0 0 1 0 1 0 1 1 1 1 0 1]
 [0 1 0 0 0 0 1 0 0 0 1 1 0]
 [1 0 1 1 1 0 0 0 0 1 1 0 0]]


In [14]:
vectorizer.get_feature_names_out()

array(['first', 'is', 'of', 'stage', 'the'], dtype=object)

In [ ]:
# encode another document
text2 = ["the puppy"]
vector = vectorizer.transform(text2)
print(vector.toarray())

[[0 0 0 0 0 0 0 1]]


In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
# list of text documents
text = ['This is the first stage of qualification'
, 'This is the second stage of qualification '
, 'And the third one'
, 'Is it the first stage again']
# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(text)
# summarize
print(vectorizer.vocabulary_)
print(vectorizer.idf_)
# encode document
vector = vectorizer.transform([text[0]])
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

{'this': 12, 'is': 3, 'the': 10, 'first': 2, 'stage': 9, 'of': 5, 'qualification': 7, 'second': 8, 'and': 1, 'third': 11, 'one': 6, 'it': 4, 'again': 0}
[1.91629073 1.91629073 1.51082562 1.22314355 1.91629073 1.51082562
 1.91629073 1.51082562 1.91629073 1.22314355 1.         1.91629073
 1.51082562]
(1, 13)
[[0.         0.         0.41706663 0.33765138 0.         0.41706663
  0.         0.41706663 0.         0.33765138 0.27605213 0.
  0.41706663]]


In [19]:
idf = vectorizer.idf_
print(dict(zip(vectorizer.get_feature_names(), idf)))

{'again': 1.916290731874155, 'and': 1.916290731874155, 'first': 1.5108256237659907, 'is': 1.2231435513142097, 'it': 1.916290731874155, 'of': 1.5108256237659907, 'one': 1.916290731874155, 'qualification': 1.5108256237659907, 'second': 1.916290731874155, 'stage': 1.2231435513142097, 'the': 1.0, 'third': 1.916290731874155, 'this': 1.5108256237659907}


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
